package ref;

public enum ItemCategory {
    HELMET,
    ARMOUR,
    PANTS,
    AMULET,
    RING,
    ONE_HANDED_MELEE_WEAPON,
    TWO_HANDED_MELEE_WEAPON,
    ONE_HANDED_GUN,
    TWO_HANDED_GUN,
    TWO_HANDED_RANGED_WEAPON
}
